# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  lint-charts:
    docker:
      - image: docker.io/alpine/helm:latest
    steps:
      - checkout
      - run:
          name: lint
          command: |
            helm version --client
            helm lint charts/*
      - run:
          name: render
          command: |
            helm version --client
            helm template charts/*
workflows:
  version: 2
  lint:
    jobs:
      - lint-charts