# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  lint-charts:
    docker:
      - image: docker.io/alpine/helm:latest
    steps:
      - run:
          name: pre-req
          command: |
            apk add --update openssh-client git
      - add_ssh_keys:
          fingerprints:
            - "59:d2:07:b9:36:1e:96:62:3b:f9:85:e7:85:b5:6b:6a"
      - checkout
      - run:
          name: lint
          command: |
            helm version --client
            helm lint charts/*
      - run:
          name: render
          command: |
            helm version --client
            helm template charts/*
workflows:
  version: 2
  lint:
    jobs:
      - lint-charts